# Generated by Django 5.2.1 on 2025-06-05 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientes',
            name='is_active',
        ),
    ]
