Coments = input("Ingrese el comentario que desea dejar: ")
Coments = Coments.strip()
Coments = Coments.lower()
Cont_Exelente = Coments.count("excelente")
print("El comentario que dejo es el siguiente: ",Coments)
print(f"Repitio la palabra Excelente {Cont_Exelente} veces")