print ("Bienvenido al programa de gestión de usuarios!")
nombre = input("Ingrese su nombre: ")
print (f"Hola, {nombre}!")
edad = int(input("Ingrese su edad: "))
print(f"{nombre}, tienes {edad} años.")