# Generated by Django 5.2.1 on 2025-05-31 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'Perfil de Usuario', 'verbose_name_plural': 'Perfiles de Usuario'},
        ),
        migrations.AlterModelOptions(
            name='usuariorol',
            options={'verbose_name': 'Asignación de Rol', 'verbose_name_plural': 'Asignaciones de Roles'},
        ),
        migrations.AddField(
            model_name='usuario',
            name='disponibilidad',
            field=models.BooleanField(default=True, help_text='Indica si el usuario está disponible', verbose_name='¿Está disponible?'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='promedio',
            field=models.FloatField(blank=True, help_text='Promedio del usuario (si aplica)', null=True, verbose_name='Promedio académico'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='apellidos',
            field=models.CharField(help_text='Apellidos del usuario', max_length=45, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombres',
            field=models.CharField(help_text='Nombres del usuario', max_length=45, verbose_name='Nombres'),
        ),
        migrations.AlterField(
            model_name='usuariorol',
            name='rol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_asignados', to='autenticacion.rol'),
        ),
        migrations.AlterField(
            model_name='usuariorol',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles_asignados', to='autenticacion.usuario'),
        ),
    ]
