# Generated by Django 5.2.1 on 2025-06-02 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0003_alter_usuario_options_alter_usuario_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'Perfil de Usuario', 'verbose_name_plural': 'Perfiles de Usuario'},
        ),
    ]
