# Generated by Django 5.2.1 on 2025-06-05 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productos',
            old_name='descripcion',
            new_name='description',
        ),
    ]
