# Generated by Django 5.2.1 on 2025-06-03 05:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código único de la asignatura', max_length=30, unique=True)),
                ('nombre', models.CharField(help_text='Nombre de la asignatura', max_length=100)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada de la asignatura')),
                ('area_estudio', models.CharField(help_text='Área de estudio de la asignatura', max_length=100)),
                ('fecha_inicio', models.DateTimeField(help_text='Fecha de inicio de la asignatura')),
                ('fecha_fin', models.DateTimeField(help_text='Fecha de finalización de la asignatura')),
            ],
            options={
                'verbose_name': 'Asignatura',
                'verbose_name_plural': 'Asignaturas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('1', 'Primero'), ('2', 'Segundo'), ('3', 'Tercero'), ('4', 'Cuarto'), ('5', 'Quinto'), ('6', 'Sexto'), ('7', 'Séptimo'), ('8', 'Octavo'), ('9', 'Noveno'), ('10', 'Décimo'), ('11', 'Once')], help_text='Grado escolar del curso', max_length=2)),
                ('paralelo', models.CharField(help_text='Número del grupo (01, 02, etc.)', max_length=2)),
                ('cupo_maximo', models.PositiveSmallIntegerField(help_text='Cupo máximo de estudiantes', validators=[django.core.validators.MinValueValidator(1)])),
                ('estado', models.BooleanField(default=True, help_text='Estado del curso (activo/inactivo)')),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='asignaturas.asignatura')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'ordering': ['nivel', 'paralelo'],
                'unique_together': {('asignatura', 'nivel', 'paralelo')},
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('LUN', 'Lunes'), ('MAR', 'Martes'), ('MIE', 'Miércoles'), ('JUE', 'Jueves'), ('VIE', 'Viernes')], help_text='Día de la semana', max_length=3)),
                ('hora_inicio', models.TimeField(help_text='Hora de inicio de la clase')),
                ('hora_fin', models.TimeField(help_text='Hora de finalización de la clase')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='asignaturas.curso')),
            ],
            options={
                'verbose_name': 'Horario',
                'verbose_name_plural': 'Horarios',
                'ordering': ['dia', 'hora_inicio'],
                'unique_together': {('curso', 'dia', 'hora_inicio')},
            },
        ),
    ]
