# Generated by Django 5.2.1 on 2025-06-04 03:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignaturas', '0001_initial'),
        ('autenticacion', '0004_alter_usuario_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatriculaCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_matricula', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de la matricula')),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('RETIRADO', 'Retirado'), ('SUSPENDIDO', 'Suspendido')], default='ACTIVO', help_text='Estado de la matrícula del estudiante', max_length=30)),
                ('curso', models.ForeignKey(help_text='Curso en el que está matriculado el estudiante', on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='asignaturas.curso')),
                ('estudiante', models.ForeignKey(help_text='Estudiante matriculado en el curso', on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='autenticacion.usuario')),
            ],
            options={
                'verbose_name': 'Matrícula en Curso',
                'verbose_name_plural': 'Matrículas en Cursos',
                'ordering': ['-fecha_matricula'],
                'unique_together': {('estudiante', 'curso')},
            },
        ),
    ]
