# Generated by Django 5.2.1 on 2025-06-04 04:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignaturas', '0002_matriculacurso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignatura',
            name='fecha_fin',
        ),
        migrations.RemoveField(
            model_name='asignatura',
            name='fecha_inicio',
        ),
        migrations.AddField(
            model_name='curso',
            name='periodo',
            field=models.CharField(choices=[('P1', 'Primer Periodo'), ('P2', 'Segundo Periodo'), ('P3', 'Tercer Periodo'), ('P4', 'Cuarto Periodo')], default='P1', help_text='Periodo académico del curso', max_length=2),
        ),
        migrations.AlterModelOptions(
            name='curso',
            options={'ordering': ['periodo', 'nivel', 'paralelo'], 'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
        migrations.AlterUniqueTogether(
            name='curso',
            unique_together={('nivel', 'paralelo', 'periodo')},
        ),
        migrations.CreateModel(
            name='AsignaturaCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horas_semanales', models.PositiveSmallIntegerField(help_text='Número de horas semanales de la asignatura', validators=[django.core.validators.MinValueValidator(1)])),
                ('fecha_inicio', models.DateField(help_text='Fecha de inicio de la asignatura en este curso')),
                ('fecha_fin', models.DateField(help_text='Fecha de finalización de la asignatura en este curso')),
                ('asignatura', models.ForeignKey(help_text='Asignatura impartida en este curso', on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='asignaturas.asignatura')),
                ('curso', models.ForeignKey(help_text='Curso al que pertenece esta asignatura', on_delete=django.db.models.deletion.CASCADE, related_name='asignaturas', to='asignaturas.curso')),
            ],
            options={
                'verbose_name': 'Asignatura en Curso',
                'verbose_name_plural': 'Asignaturas en Cursos',
                'ordering': ['curso', 'asignatura'],
                'unique_together': {('curso', 'asignatura')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='horario',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='horario',
            name='asignatura_curso',
            field=models.ForeignKey(blank=True, help_text='Asignatura del curso para este horario', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='asignaturas.asignaturacurso'),
        ),
        migrations.AlterUniqueTogether(
            name='horario',
            unique_together={('asignatura_curso', 'dia', 'hora_inicio')},
        ),
        migrations.RemoveField(
            model_name='curso',
            name='asignatura',
        ),
        migrations.RemoveField(
            model_name='horario',
            name='curso',
        ),
    ]
