# Generated by Django 5.2.1 on 2025-06-10 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asignaturas', '0001_initial'),
        ('autenticacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoFalta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('nivel', models.CharField(choices=[('LEVE', 'Falta Leve'), ('GRAVE', 'Falta Grave'), ('MUY_GRAVE', 'Falta Muy Grave')], max_length=30)),
            ],
            options={
                'verbose_name': 'Tipo de Falta',
                'verbose_name_plural': 'Tipos de Faltas',
                'ordering': ['nivel', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='RegistroComportamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('POSITIVO', 'Observación Positiva'), ('NEGATIVO', 'Observación Negativa')], max_length=30)),
                ('descripcion', models.TextField()),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_comportamiento', to='autenticacion.usuario')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asignaturas.periodoacademico')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_realizados', to='autenticacion.usuario')),
                ('tipo_falta', models.ForeignKey(blank=True, help_text='Solo aplica para observaciones negativas', null=True, on_delete=django.db.models.deletion.SET_NULL, to='comportamiento.tipofalta')),
            ],
            options={
                'verbose_name': 'Registro de Comportamiento',
                'verbose_name_plural': 'Registros de Comportamiento',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Compromiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('fecha_compromiso', models.DateField()),
                ('fecha_seguimiento', models.DateField()),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En Proceso'), ('CUMPLIDO', 'Cumplido'), ('INCUMPLIDO', 'Incumplido')], default='PENDIENTE', max_length=15)),
                ('observaciones', models.TextField(blank=True)),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compromisos', to='comportamiento.registrocomportamiento')),
            ],
            options={
                'verbose_name': 'Compromiso',
                'verbose_name_plural': 'Compromisos',
                'ordering': ['fecha_compromiso'],
            },
        ),
    ]
