# Generated by Django 5.2.1 on 2025-06-10 05:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asignaturas', '0001_initial'),
        ('autenticacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('porcentaje', models.FloatField(help_text='Porcentaje que representa esta actividad en la calificación del período', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Porcentaje de la evaluación')),
            ],
            options={
                'verbose_name': 'Tipo de Actividad',
                'verbose_name_plural': 'Tipos de Actividades',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('fecha_asignacion', models.DateField(verbose_name='Fecha de asignación')),
                ('fecha_entrega', models.DateField(verbose_name='Fecha de entrega')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('periodo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='asignaturas.periodoacademico', verbose_name='Período Académico')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actividades', to='notas.tipoactividad', verbose_name='Tipo de Actividad')),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
                'ordering': ['periodo', 'fecha_entrega'],
            },
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('valor', models.FloatField(help_text='Valor numérico de la nota (0-10). Se permite hasta 2 decimales.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Valor de la nota')),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones o comentarios sobre la nota', null=True, verbose_name='Observaciones')),
                ('es_recuperacion', models.BooleanField(default=False, help_text='Indica si esta nota corresponde a una recuperación', verbose_name='¿Es recuperación?')),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='notas.actividad', verbose_name='Actividad')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='autenticacion.usuario', verbose_name='Estudiante')),
            ],
            options={
                'verbose_name': 'Nota',
                'verbose_name_plural': 'Notas',
                'ordering': ['-actividad__fecha_entrega'],
                'unique_together': {('estudiante', 'actividad')},
            },
        ),
    ]
