# Generated by Django 5.2.1 on 2025-06-06 16:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='es_recuperacion',
            field=models.BooleanField(default=False, help_text='Indica si la nota se puede recuperar', verbose_name='¿Es recuperación?'),
        ),
        migrations.AlterField(
            model_name='nota',
            name='valor',
            field=models.FloatField(help_text='Valor numérico de la nota (0-10). Se permite hasta 2 decimales', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Valor de la nota'),
        ),
    ]
