# Generated by Django 5.2.1 on 2025-06-10 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asignaturas', '0001_initial'),
        ('autenticacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('hora', models.TimeField(verbose_name='Hora')),
                ('estado', models.CharField(choices=[('PRESENTE', 'Presente'), ('AUSENTE', 'Ausente'), ('TARDE', 'Tardanza'), ('JUSTIFICADA', 'Con Justificación')], max_length=30)),
                ('justificacion', models.TextField(blank=True, null=True, verbose_name='Justificación')),
                ('validada', models.BooleanField(default=False, verbose_name='¿Validada?')),
                ('matricula', models.ForeignKey(blank=True, help_text='Matrícula del estudiante en el curso', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='asignaturas.matriculacurso', verbose_name='Matrícula del Estudiante')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asistencias_old', to='autenticacion.usuario', verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Asistencia',
                'verbose_name_plural': 'Asistencias',
                'ordering': ['-fecha', '-hora'],
                'unique_together': {('matricula', 'fecha', 'hora')},
            },
        ),
    ]
