# Generated by Django 5.2.1 on 2025-06-03 01:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('autenticacion', '0004_alter_usuario_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('hora', models.TimeField(verbose_name='Hora')),
                ('estado', models.CharField(choices=[('PRESENTE', 'Presente'), ('AUSENTE', 'Ausente'), ('TARDE', 'Tardanza'), ('JUSTIFICADA', 'Con Justificación')], default='AUSENTE', max_length=30, verbose_name='Estado')),
                ('justificacion', models.TextField(blank=True, null=True, verbose_name='Justificación')),
                ('validada', models.BooleanField(default=False, verbose_name='¿Validada?')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='autenticacion.usuario', verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Asistencia',
                'verbose_name_plural': 'Asistencias',
                'ordering': ['-fecha', '-hora'],
                'unique_together': {('usuario', 'fecha', 'hora')},
            },
        ),
    ]
