# Generated by Django 5.2.1 on 2025-06-04 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignaturas', '0002_matriculacurso'),
        ('asistencias', '0002_alter_asistencia_estado'),
        ('autenticacion', '0004_alter_usuario_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='asistencia',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='matricula',
            field=models.ForeignKey(blank=True, help_text='Matrícula del estudiante en el curso', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='asignaturas.matriculacurso', verbose_name='Matrícula del Estudiante'),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asistencias_old', to='autenticacion.usuario', verbose_name='Usuario'),
        ),
        migrations.AlterUniqueTogether(
            name='asistencia',
            unique_together={('matricula', 'fecha', 'hora')},
        ),
    ]
