# Generated by Django 5.2.1 on 2025-05-28 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='products',
        ),
        migrations.DeleteModel(
            name='suppliers',
        ),
    ]
